[package]
name = "lieutenant"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
lieutenant-macros = { path =  "macros" }

anyhow = "1.0"
thiserror = "1.0"
slab = "0.4"
smallvec = "1.4"
bstr = "0.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dispatcher"
harness = false

[workspace]
members = [".", "macros"]
